### PR TITLE
feat: promote to 1.0.0

### PR DESCRIPTION
**Pull request by manuelmenzella-google**
Release-As: 1.0.0

### CODE REVIEW

**Comment by anguillanneuf** [comment]
Fixes #604

**Review by anguillanneuf — CHANGES_REQUESTED** [review]
@manuelmenzella-google  Can you update your commit message to `feat: promote google-cloud-pubsulblite to 1.0.0`? 
Example: https://github.com/googleapis/java-memcache/pull/314

**Comment by chingor13** [comment]
We can change the title of the PR and use merge-on-green (add the `automerge` label)

**Comment by manuelmenzella-google** [comment]
Sounds good -- I've renamed the commit.

@chingor13 Tianzi mentioned that she was looking into whether the split of versions.txt was enough to release these two artifacts independently. I'm holding off adding the automerge label until then.

**Review by anguillanneuf — APPROVED** [review]

**Comment by anguillanneuf** [comment]
@manuelmenzella-google Jeff is fully aware of our needs :-)

This PR is okay to merge - we will hold off on proposed releases until 1) next week's major bump to all Java clients (may exclude Lite) 2) we think they are indeed what we want.

**Pull request merged**
